### ISSUE TITLE
Command to export existing records

### ISSUE THREAD

**Issue by khromov** [jungaretti/bacon#23]
It would be extremely useful if Bacon could also export records into the YAML format, making it possible to migrate records between porkbun domains! 🐷

**Comment by jungaretti** [comment]
Good news! This already exists, but it isn't documented. The command is `bacon print <domain>` and here's the code: https://github.com/jungaretti/bacon/blob/main/cmd/print.go

I need to add its details to Bacon's [`README.md`](https://github.com/jungaretti/bacon/blob/main/README.md#usage)

**Comment by khromov** [comment]
Excellent, thank you!

**Comment by jungaretti** [comment]
Let's leave this open until I make a PR to update the docs!
