### ISSUE TITLE
Question:  Print from domains not in porkbun account

### ISSUE THREAD

**Issue by sbutlerjr** [jungaretti/bacon#34]
Any plans to support the print option from generic DNS API providers so that this could be used as a DNS migration tool?

Something like:
```
GET: https://networkcalc.com/api/dns/lookup/example.com
```
and print out the entries in the YAML format.   Then that YAML could be used to deploy those DNS entries into Porkbun and this would be a great DNS migration tool!

**Comment by jungaretti** [comment]
Interesting idea. Unfortunately, I don't plan to add official support for these providers anytime soon. I don't use them enough to test and maintain the necessary code. For now, Bacon only supports Porkbun.

That being said, it seems like you could use that API response to craft a Bacon config file quite easily. It includes all of the data that you need.

If your domain is already hosted on Bacon, you can use `bacon print <domain>` to print its config file: https://github.com/jungaretti/bacon?tab=readme-ov-file#print-domain
