### ISSUE TITLE
Use new api.porkbun.com hostname

### ISSUE THREAD

**Issue by susnick** [jungaretti/bacon#39]
From email

Hello there,

The reason you are receiving this email is because you have an API key associated with your account. In order to ensure that any apps or tools you may have that utilize our API, we wanted to let you know about some upcoming critical updates.

We know these kinds of changes are annoying but the time has come to separate the processing of incoming API commands from our website. In previous documentation the hostname porkbun.com was used for the API but we have recently updated it to api.porkbun.com and in the near future will start enforcing its use. Please update the hostname for our API to api.porkbun.com as soon as possible.

CRITICAL UPDATE DETAILS

Type: API Hostname Change

Old Value: porkbun.com

New Value: api.porkbun.com

Deadline: 2024-12-01 00:00:00 UTC

Please note that after the deadline, API calls made to the old hostname will no longer be allowed. If you have any questions or concerns please contact support.

**Comment by jungaretti** [comment]
This is fixed in [Bacon v1.3](https://github.com/jungaretti/bacon/releases/tag/v1.3)

Thanks @susnick for opening this issue and submitting a fix quickly.
